Repository deannabosschert/Matcher, pull requests merged in 2021-06, with the labels that each got.

#30 Feat/build scripts
  dist/css/main.css
  dist/img/pompebled.svg
  dist/js/createLeafletMap.js
  favicon.ico
  gulpfile.js
  index.js
  package-lock.json
  package.json
  src/js/createLeafletMap.js
  src/scss/reset.css
  src/scss/style.scss
  views/layouts/main.hbs
Labels: feature

#31 Feat/pwa
  controllers/authController.js
  dist/app.webmanifest
  dist/img/icons/favicon.png
  dist/img/icons/icon240.png
  dist/sw.js
  index.js
  package-lock.json
  package.json
  router/index.js
  src/js/createLeafletMap.js
  views/layouts/main.hbs
  views/offline.hbs
Labels: feature

#35 Refactor/controllers (#33)
  controllers/authController.js
  controllers/matchController.js
  controllers/profileController.js
  controllers/routeController.js
  router/index.js
Labels: coding, help wanted

#37 Feat/predev scripts
  gulpfile.js
  package.json
Labels: bug, coding

#44 Develop
  .gitignore
Labels: organization
